spring:
  profiles:
    group:
      development:
        - common
        - blue
        - green
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(P5J7Ioi0OprueUrt3fFv2A==)
    password: ENC(eCb5NnNqDSeixJJVCqt0Cw==)
    url: ENC(FfK3luDDW5RcfTf1Y1ANsU5fbfTK71q6ycvpGMufvdnRfihWWrBlpm6NV6l0liIOGAiXlQhyAK5JQJYcYhrKIzWfyKBYBLbB1hNl4kPyA64=)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB


cloud:
  aws:
    s3:
      bucket: ENC(Y4/w6+PLIdoUTI9TcQf7/echDgJEldvj3uF8hXTHGqw=)
    credentials:
      access-key: ENC(d+zPWsAtzmUL8Ve0cxpeoGulXzgyrIsDzONSCglQAXo=)
      secret-key: ENC(7UzrnKPq0ZAolzrPxTRNC9tcbw0ETQzyrKDS5454M0YjOtPzVQOJQjqLPZbNSTLXzWDnLDyZq4o=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false



---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080


---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081